<?php
define("CONST_ENCERRADO_PELO_ANALISTA", "Encerrado pelo analista");
define("CONST_SPAM", "Spam");
define("CONST_FILA_DE_SPAM", 15);


define("CONST_TICKET_ESTADO_ENCERRADO", 2);
define("CONST_TICKET_ESTADO_AGUARDANDO_VALIDACAO", 7);

define("CONST_DYNAMIC_FIELD_DEPARTAMENTO", 19);
define("CONST_DYNAMIC_FIELD_RESPOSTA_SATISFACAO", 21);


define("CONST_TICKET_TYPE_INCIDENTE", 2);
define("CONST_TICKET_TYPE_REQUISICAO", 4);
